import numpy as np
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(12,5))
# (i)
ax1=fig.add_subplot(1,2,1,projection='3d')
x1=np.linspace(1,7,200)
y1=np.linspace(-4,4,200)
X1,Y1=np.meshgrid(x1,y1)
Z1=Y1**2-2*Y1*np.cos(X1)
ax1.plot_surface(X1,Y1,Z1,cmap='viridis')
ax1.set_title(r'(i) $f(x,y)=y^2-2y \cos x$')
ax1.set_xlabel('x')
ax1.set_ylabel('y')
ax1.set_zlabel('f(x, y)')
# (ii)
ax2=fig.add_subplot(1,2,2,projection='3d')
x2=np.linspace(0,2*np.pi,200)
y2=np.linspace(0,2*np.pi,200)
X2,Y2=np.meshgrid(x2,y2)
Z2=np.abs(np.sin(X2)*np.sin(Y2))
ax2.plot_surface(X2,Y2,Z2,cmap='plasma')
ax2.set_title(r'(ii) $f(x,y)= |\sin x \sin y|$')
ax2.set_xlabel('x')
ax2.set_ylabel('y')
ax2.set_zlabel('f(x, y)')
plt.tight_layout()
plt.show()